sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

jobs:
    include:
    - script: ignore # Skip default stage test

    - stage: test building of docker images
      script: docker build -t goloschain/golos:test -f share/golosd/docker/Dockerfile-test .
    - script: docker build -t goloschain/golos:develop .
    - script: docker build -t goloschain/golos:develop -f share/golosd/docker/Dockerfile-testnet .
    - script: docker build -t goloschain/golos:develop -f share/golosd/docker/Dockerfile-lowmem .

    - stage: publish latest docker images
      if: branch = master
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t goloschain/golos:latest .
        - docker images
        - docker tag goloschain/golos:latest goloschain/golos:latest
        - docker push goloschain/golos:latest

    - script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t goloschain/golos:latest-testnet -f share/golosd/docker/Dockerfile-testnet .
        - docker images
        - docker tag goloschain/golos:latest-testnet goloschain/golos:latest-testnet
        - docker push goloschain/golos:lastest-testnet

    - script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t goloschain/golos:latest-lowmem -f share/golosd/docker/Dockerfile-lowmem .
        - docker images
        - docker tag goloschain/golos:latest-lowmem goloschain/golos:latest-lowmem
        - docker push goloschain/golos:lastest-lowmem

    - stage: publish "$TRAVIS_TAG" docker images
      if: tag IS present
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t goloschain/golos:"$TRAVIS_TAG" .
        - docker images
        - docker tag goloschain/golos:"$TRAVIS_TAG" goloschain/golos:"$TRAVIS_TAG"
        - docker push goloschain/golos:"$TRAVIS_TAG"

    - script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t goloschain/golos:"$TRAVIS_TAG"-testnet -f share/golosd/docker/Dockerfile-testnet .
        - docker images
        - docker tag goloschain/golos:"$TRAVIS_TAG"-testnet goloschain/golos:"$TRAVIS_TAG"-testnet
        - docker push goloschain/golos:"$TRAVIS_TAG"-testnet

    - script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t goloschain/golos:"$TRAVIS_TAG"-lowmem -f share/golosd/docker/Dockerfile-lowmem .
        - docker images
        - docker tag goloschain/golos:"$TRAVIS_TAG"-lowmem goloschain/golos:"$TRAVIS_TAG"-lowmem
        - docker push goloschain/golos:"$TRAVIS_TAG"-lowmem
