sudo: required

language: cpp

addons:
  ssh_known_hosts: developers.golos.io
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
  - bash deploy/deploy.sh


