sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker build -t goloschain/golos:"$TRAVIS_TAG" . ;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t goloschain/golos:latest . ;
    else
      docker build -t goloschain/golos:test -f share/golosd/docker/Dockerfile-test . ;
      docker build -t goloschain/golos:develop . ;
      docker build -t goloschain/golos:lowmem -f share/golosd/docker/Dockerfile-lowmem-small . ;
      docker build -t goloschain/golos:testnet -f share/golosd/docker/Dockerfile-testnet . ;
    fi
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push goloschain/golos:latest;
      bash deploy/deploy.sh;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push goloschain/golos:"$TRAVIS_TAG";
    fi
