sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"
  - echo "Installing mongo-c-driver"
  - sudo apt-get -qq update
  - sudo apt-get -y install pkg-config libssl-dev libsasl2-dev
  - wget https://github.com/mongodb/mongo-c-driver/releases/download/1.9.5/mongo-c-driver-1.9.5.tar.gz
  - tar xzf mongo-c-driver-1.9.5.tar.gz
  - cd mongo-c-driver-1.9.5
  - ./configure --disable-automatic-init-and-cleanup --enable-static
  - make
  - sudo make install
  - echo "Installing mongo-cxx-driver"
  - git clone https://github.com/mongodb/mongo-cxx-driver.git --branch releases/v3.2 --depth 1
  - cd mongo-cxx-driver
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - sudo make EP_mnmlstc_core
  - make
  - sudo make install
  - sudo apt-get -y install mongodb

script:
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker build -t goloschain/golos:"$TRAVIS_TAG" . ;
    else
      docker build -t goloschain/golos:latest . ;
    fi
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push goloschain/golos:latest;
      bash deploy/deploy.sh;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push goloschain/golos:"$TRAVIS_TAG";
    fi
