sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script: ./travis-run-tests.sh

deploy:
  skip_cleanup: true
  on:
    tag: true


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push goloschain/golos:master;
    fi
  - if [ -n "$TRAVIS_TAG"] && [ "$TRAVIS_TAG" != ""]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push goloschain/golos:$TRAVIS_TAG;
    fi
