FROM phusion/baseimage:0.9.19

ENV LANG=en_US.UTF-8

RUN \
    apt-get update && \
    apt-get install -y \
        autoconf \
        automake \
        autotools-dev \
        bsdmainutils \
        build-essential \
        cmake \
        doxygen \
        git \
        ccache\
        libboost-all-dev \
        libreadline-dev \
        libssl-dev \
        libtool \
        ncurses-dev \
        pbzip2 \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip3 install gcovr

# installing mongo drivers
RUN \
    echo "Installing mongo-c-driver" && \
    apt-get -qq update && \
    apt-get install -y \
        pkg-config \
        libssl-dev \
        libsasl2-dev \
        wget \
    && \
    wget https://github.com/mongodb/mongo-c-driver/releases/download/1.9.5/mongo-c-driver-1.9.5.tar.gz && \
    tar xzf mongo-c-driver-1.9.5.tar.gz && \
    cd mongo-c-driver-1.9.5 && \
    ./configure --disable-automatic-init-and-cleanup --enable-static && \
    make && \
    make install && \
    cd .. && \
    rm -rf mongo-c-driver-1.9.5 && \
    echo "Installing mongo-cxx-driver" && \
    git clone https://github.com/mongodb/mongo-cxx-driver.git --branch releases/v3.2 --depth 1 && \
    cd mongo-cxx-driver/build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .. && \
    make EP_mnmlstc_core && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf mongo-cxx-driver
# end

ADD . /usr/local/src/golos

RUN \
    cd /usr/local/src/golos && \
    git submodule deinit -f . && \
    git submodule update --init --recursive -f && \
    mkdir build && \
    cd build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_GOLOS_TESTNET=TRUE \
        -DLOW_MEMORY_NODE=FALSE \
        -DMAX_19_VOTED_WITNESSES=TRUE \
        .. && \
    make -j$(nproc) chain_test plugin_test && \
    ./tests/chain_test --log_level=message --report_level=detailed && \
    ./tests/plugin_test --log_level=message --report_level=detailed

# isn't used now, but can be used later ...
#
# RUN \
#    cd /usr/local/src/golos && \
#    rm -rf build && \
#    git submodule update --init --recursive -f && \
#    mkdir build && \
#    cd build && \
#    cmake \
#        -DCMAKE_BUILD_TYPE=Debug \
#        -DENABLE_COVERAGE_TESTING=TRUE \
#        -DBUILD_GOLOS_TESTNET=TRUE \
#        -DLOW_MEMORY_NODE=FALSE \
#        -DMAX_19_VOTED_WITNESSES=TRUE \
#        .. && \
#    make -j$(nproc) chain_test plugin_test && \
#    ./tests/chain_test && \
#    ./tests/plugin_test && \
#    mkdir -p /var/cobertura && \
#    gcovr --object-directory="../" --root=../ --xml-pretty --gcov-exclude=".*tests.*" --gcov-exclude=".*fc.*"  --output="/var/cobertura/coverage.xml"
